apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecommerce-db-pv
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/ecommerce-db" # Le dossier sur ton PC qui gardera les données
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-db-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi