name: CI-Ecommerce

on:
  push:
    branches: [ "main" ]

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Build du Frontend (Générer le dossier dist)
        run: |
          cd frontend
          npm install
          npm run build

      - name: Vérifier le build Docker Backend
        run: |
          docker build -t test-backend ./backend

      - name: Vérifier le build Docker Frontend
        run: |
          docker build -t test-frontend ./frontend

      - name: Test de l'infrastructure Docker Compose
        run: |
          docker compose config