name: CI-Ecommerce

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build du Frontend (Générer le dossier dist)
        run: |
          cd frontend
          npm install
          npm run build

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push Backend
        uses: docker/build-push-action@v5
        with: 
          context: ./backend
          push: true
          tags: herimk/Ecommerce-backend:latest

      - name: Build et Push Frontend
        uses: docker/build-push-action@v5
        with: 
          context: ./frontend
          push: true
          tags: herimk/Ecommerce-frontend:latest
